// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YuGiOhForbiddenAPI.Persistence;

#nullable disable

namespace YuGiOhForbiddenAPI.Persistence.Migrations
{
    [DbContext(typeof(YuGiOhDbContext))]
    partial class YuGiOhDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YuGiOhForbiddenAPI.Model.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Atk")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int?>("Def")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Card");

                    b.HasDiscriminator<string>("Type").HasValue("Card");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("YuGiOhForbiddenAPI.Entities.Equip", b =>
                {
                    b.HasBaseType("YuGiOhForbiddenAPI.Model.Card");

                    b.HasDiscriminator().HasValue("Equip");
                });

            modelBuilder.Entity("YuGiOhForbiddenAPI.Entities.Monster", b =>
                {
                    b.HasBaseType("YuGiOhForbiddenAPI.Model.Card");

                    b.HasDiscriminator().HasValue("Monster");
                });

            modelBuilder.Entity("YuGiOhForbiddenAPI.Entities.Trap", b =>
                {
                    b.HasBaseType("YuGiOhForbiddenAPI.Model.Card");

                    b.HasDiscriminator().HasValue("Trap");
                });
#pragma warning restore 612, 618
        }
    }
}
